// Code generated by gotdgen, DO NOT EDIT.

package tdapi

import (
	"context"
	"errors"
	"fmt"
	"sort"
	"strings"

	"go.uber.org/multierr"

	"go.mau.fi/mautrix-telegram/pkg/gotd/bin"
	"go.mau.fi/mautrix-telegram/pkg/gotd/tdjson"
	"go.mau.fi/mautrix-telegram/pkg/gotd/tdp"
	"go.mau.fi/mautrix-telegram/pkg/gotd/tgerr"
)

// No-op definition for keeping imports.
var (
	_ = bin.Buffer{}
	_ = context.Background()
	_ = fmt.Stringer(nil)
	_ = strings.Builder{}
	_ = errors.Is
	_ = multierr.AppendInto
	_ = sort.Ints
	_ = tdp.Format
	_ = tgerr.Error{}
	_ = tdjson.Encoder{}
)

// GetUpgradedGiftEmojiStatusesRequest represents TL type `getUpgradedGiftEmojiStatuses#97c0bf95`.
type GetUpgradedGiftEmojiStatusesRequest struct {
}

// GetUpgradedGiftEmojiStatusesRequestTypeID is TL type id of GetUpgradedGiftEmojiStatusesRequest.
const GetUpgradedGiftEmojiStatusesRequestTypeID = 0x97c0bf95

// Ensuring interfaces in compile-time for GetUpgradedGiftEmojiStatusesRequest.
var (
	_ bin.Encoder     = &GetUpgradedGiftEmojiStatusesRequest{}
	_ bin.Decoder     = &GetUpgradedGiftEmojiStatusesRequest{}
	_ bin.BareEncoder = &GetUpgradedGiftEmojiStatusesRequest{}
	_ bin.BareDecoder = &GetUpgradedGiftEmojiStatusesRequest{}
)

func (g *GetUpgradedGiftEmojiStatusesRequest) Zero() bool {
	if g == nil {
		return true
	}

	return true
}

// String implements fmt.Stringer.
func (g *GetUpgradedGiftEmojiStatusesRequest) String() string {
	if g == nil {
		return "GetUpgradedGiftEmojiStatusesRequest(nil)"
	}
	type Alias GetUpgradedGiftEmojiStatusesRequest
	return fmt.Sprintf("GetUpgradedGiftEmojiStatusesRequest%+v", Alias(*g))
}

// TypeID returns type id in TL schema.
//
// See https://core.telegram.org/mtproto/TL-tl#remarks.
func (*GetUpgradedGiftEmojiStatusesRequest) TypeID() uint32 {
	return GetUpgradedGiftEmojiStatusesRequestTypeID
}

// TypeName returns name of type in TL schema.
func (*GetUpgradedGiftEmojiStatusesRequest) TypeName() string {
	return "getUpgradedGiftEmojiStatuses"
}

// TypeInfo returns info about TL type.
func (g *GetUpgradedGiftEmojiStatusesRequest) TypeInfo() tdp.Type {
	typ := tdp.Type{
		Name: "getUpgradedGiftEmojiStatuses",
		ID:   GetUpgradedGiftEmojiStatusesRequestTypeID,
	}
	if g == nil {
		typ.Null = true
		return typ
	}
	typ.Fields = []tdp.Field{}
	return typ
}

// Encode implements bin.Encoder.
func (g *GetUpgradedGiftEmojiStatusesRequest) Encode(b *bin.Buffer) error {
	if g == nil {
		return fmt.Errorf("can't encode getUpgradedGiftEmojiStatuses#97c0bf95 as nil")
	}
	b.PutID(GetUpgradedGiftEmojiStatusesRequestTypeID)
	return g.EncodeBare(b)
}

// EncodeBare implements bin.BareEncoder.
func (g *GetUpgradedGiftEmojiStatusesRequest) EncodeBare(b *bin.Buffer) error {
	if g == nil {
		return fmt.Errorf("can't encode getUpgradedGiftEmojiStatuses#97c0bf95 as nil")
	}
	return nil
}

// Decode implements bin.Decoder.
func (g *GetUpgradedGiftEmojiStatusesRequest) Decode(b *bin.Buffer) error {
	if g == nil {
		return fmt.Errorf("can't decode getUpgradedGiftEmojiStatuses#97c0bf95 to nil")
	}
	if err := b.ConsumeID(GetUpgradedGiftEmojiStatusesRequestTypeID); err != nil {
		return fmt.Errorf("unable to decode getUpgradedGiftEmojiStatuses#97c0bf95: %w", err)
	}
	return g.DecodeBare(b)
}

// DecodeBare implements bin.BareDecoder.
func (g *GetUpgradedGiftEmojiStatusesRequest) DecodeBare(b *bin.Buffer) error {
	if g == nil {
		return fmt.Errorf("can't decode getUpgradedGiftEmojiStatuses#97c0bf95 to nil")
	}
	return nil
}

// EncodeTDLibJSON implements tdjson.TDLibEncoder.
func (g *GetUpgradedGiftEmojiStatusesRequest) EncodeTDLibJSON(b tdjson.Encoder) error {
	if g == nil {
		return fmt.Errorf("can't encode getUpgradedGiftEmojiStatuses#97c0bf95 as nil")
	}
	b.ObjStart()
	b.PutID("getUpgradedGiftEmojiStatuses")
	b.Comma()
	b.StripComma()
	b.ObjEnd()
	return nil
}

// DecodeTDLibJSON implements tdjson.TDLibDecoder.
func (g *GetUpgradedGiftEmojiStatusesRequest) DecodeTDLibJSON(b tdjson.Decoder) error {
	if g == nil {
		return fmt.Errorf("can't decode getUpgradedGiftEmojiStatuses#97c0bf95 to nil")
	}

	return b.Obj(func(b tdjson.Decoder, key []byte) error {
		switch string(key) {
		case tdjson.TypeField:
			if err := b.ConsumeID("getUpgradedGiftEmojiStatuses"); err != nil {
				return fmt.Errorf("unable to decode getUpgradedGiftEmojiStatuses#97c0bf95: %w", err)
			}
		default:
			return b.Skip()
		}
		return nil
	})
}

// GetUpgradedGiftEmojiStatuses invokes method getUpgradedGiftEmojiStatuses#97c0bf95 returning error if any.
func (c *Client) GetUpgradedGiftEmojiStatuses(ctx context.Context) (*EmojiStatuses, error) {
	var result EmojiStatuses

	request := &GetUpgradedGiftEmojiStatusesRequest{}
	if err := c.rpc.Invoke(ctx, request, &result); err != nil {
		return nil, err
	}
	return &result, nil
}
