---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: config
stringData:
  BOT_TOKEN: "1111111111:AAG1SomeBotTokenFromBotFather-1337a"
  APP_ID: "0123456"
  APP_HASH: "0123456789abcdef0123456789abcdef"
