// Code generated by gotdgen, DO NOT EDIT.

package tg

import (
	"context"
	"errors"
	"fmt"
	"sort"
	"strings"

	"go.uber.org/multierr"

	"go.mau.fi/mautrix-telegram/pkg/gotd/bin"
	"go.mau.fi/mautrix-telegram/pkg/gotd/tdjson"
	"go.mau.fi/mautrix-telegram/pkg/gotd/tdp"
	"go.mau.fi/mautrix-telegram/pkg/gotd/tgerr"
)

// No-op definition for keeping imports.
var (
	_ = bin.Buffer{}
	_ = context.Background()
	_ = fmt.Stringer(nil)
	_ = strings.Builder{}
	_ = errors.Is
	_ = multierr.AppendInto
	_ = sort.Ints
	_ = tdp.Format
	_ = tgerr.Error{}
	_ = tdjson.Encoder{}
)

// longVector is a box for Vector<long>
type longVector struct {
	// Elements of Vector<long>
	Elems []int64
}

// longVectorTypeID is TL type id of longVector.
const longVectorTypeID = bin.TypeVector

// Ensuring interfaces in compile-time for longVector.
var (
	_ bin.Encoder     = &longVector{}
	_ bin.Decoder     = &longVector{}
	_ bin.BareEncoder = &longVector{}
	_ bin.BareDecoder = &longVector{}
)

func (vec *longVector) Zero() bool {
	if vec == nil {
		return true
	}
	if !(vec.Elems == nil) {
		return false
	}

	return true
}

// String implements fmt.Stringer.
func (vec *longVector) String() string {
	if vec == nil {
		return "longVector(nil)"
	}
	type Alias longVector
	return fmt.Sprintf("longVector%+v", Alias(*vec))
}

// FillFrom fills longVector from given interface.
func (vec *longVector) FillFrom(from interface {
	GetElems() (value []int64)
}) {
	vec.Elems = from.GetElems()
}

// TypeID returns type id in TL schema.
//
// See https://core.telegram.org/mtproto/TL-tl#remarks.
func (*longVector) TypeID() uint32 {
	return longVectorTypeID
}

// TypeName returns name of type in TL schema.
func (*longVector) TypeName() string {
	return ""
}

// TypeInfo returns info about TL type.
func (vec *longVector) TypeInfo() tdp.Type {
	typ := tdp.Type{
		Name: "",
		ID:   longVectorTypeID,
	}
	if vec == nil {
		typ.Null = true
		return typ
	}
	typ.Fields = []tdp.Field{
		{
			Name:       "Elems",
			SchemaName: "Elems",
		},
	}
	return typ
}

// Encode implements bin.Encoder.
func (vec *longVector) Encode(b *bin.Buffer) error {
	if vec == nil {
		return fmt.Errorf("can't encode Vector<long> as nil")
	}

	return vec.EncodeBare(b)
}

// EncodeBare implements bin.BareEncoder.
func (vec *longVector) EncodeBare(b *bin.Buffer) error {
	if vec == nil {
		return fmt.Errorf("can't encode Vector<long> as nil")
	}
	b.PutVectorHeader(len(vec.Elems))
	for _, v := range vec.Elems {
		b.PutLong(v)
	}
	return nil
}

// Decode implements bin.Decoder.
func (vec *longVector) Decode(b *bin.Buffer) error {
	if vec == nil {
		return fmt.Errorf("can't decode Vector<long> to nil")
	}

	return vec.DecodeBare(b)
}

// DecodeBare implements bin.BareDecoder.
func (vec *longVector) DecodeBare(b *bin.Buffer) error {
	if vec == nil {
		return fmt.Errorf("can't decode Vector<long> to nil")
	}
	{
		headerLen, err := b.VectorHeader()
		if err != nil {
			return fmt.Errorf("unable to decode Vector<long>: field Elems: %w", err)
		}

		if headerLen > 0 {
			vec.Elems = make([]int64, 0, headerLen%bin.PreallocateLimit)
		}
		for idx := 0; idx < headerLen; idx++ {
			value, err := b.Long()
			if err != nil {
				return fmt.Errorf("unable to decode Vector<long>: field Elems: %w", err)
			}
			vec.Elems = append(vec.Elems, value)
		}
	}
	return nil
}

// GetElems returns value of Elems field.
func (vec *longVector) GetElems() (value []int64) {
	if vec == nil {
		return
	}
	return vec.Elems
}
